name: "linto_stt_fr_fastconformer_pc"

init_from_nemo_model: "nvidia/stt_fr_fastconformer_hybrid_large_pc"

model:
  sample_rate: 16000
  compute_eval_loss: false    # eval samples can be very long and exhaust memory. Disable computation of transducer loss during validation/testing with this flag.
  log_prediction: false       # enables logging sample predictions in the output during training
  ctc_reduction: 'mean_volume'
  skip_nan_grad: false
  freeze_encoder: false
  seed: 42
  train_ds:
    manifest_filepath:
      - train_manifests/manifest_cleaned_ACSYNT_casepunc_max30.jsonl
      - train_manifests/manifest_cleaned_AfricanAccentedFrench_recasepunc_max30_train.jsonl
      - train_manifests/manifest_cleaned_CFPB_recasepunc_max30.jsonl
      - train_manifests/manifest_cleaned_CFPP2000_recasepunc_max30_train.jsonl
      - train_manifests/manifest_cleaned_CLAPI_recasepunc_max30.jsonl
      - train_manifests/manifest_cleaned_CommonVoice_casepunc_max30_train.jsonl
      - train_manifests/manifest_cleaned_ESLO_recasepunc_max30.jsonl
      - train_manifests/manifest_cleaned_FLEURS_casepunc_max30_train.jsonl
      - train_manifests/manifest_cleaned_LINAGORA_Meetings_casepunc_max30.jsonl
      - train_manifests/manifest_cleaned_LVL-Atril-CTFAR_casepunc_max30.jsonl
      - train_manifests/manifest_cleaned_LVL-Atril-CTFNN1_casepunc_max30.jsonl
      - train_manifests/manifest_cleaned_LesVocaux_recasepunc_max30.jsonl
      - train_manifests/manifest_cleaned_Multilingual_LibriSpeech_recasepunc_max30_train.jsonl
      - train_manifests/manifest_cleaned_Multilingual_TEDx_casepunc_max30_train.jsonl
      - train_manifests/manifest_cleaned_OFROM_recasepunc_max30_train.jsonl
      - train_manifests/manifest_cleaned_PFC_casepunc_max30.jsonl
      - train_manifests/manifest_cleaned_PxSLU_recasepunc_max30.jsonl
      - train_manifests/manifest_cleaned_SimSamu_casepunc_max30.jsonl
      - train_manifests/manifest_cleaned_TCOF_Adultes_recasepunc_max30_train.jsonl
      - train_manifests/manifest_cleaned_TCOF_Enfants_recasepunc_max30_train.jsonl
      - train_manifests/manifest_cleaned_VoxForge_recasepunc_max30.jsonl
      - train_manifests/manifest_cleaned_VoxPopuli_casepunc_max30_train.jsonl
      - train_manifests/manifest_cleaned_YouTubeFr_casepunc_max30_split0.jsonl
      - train_manifests/manifest_cleaned_YouTubeFr_casepunc_max30_split1.jsonl
      - train_manifests/manifest_cleaned_YouTubeFr_casepunc_max30_split2.jsonl
      - train_manifests/manifest_cleaned_YouTubeFr_casepunc_max30_split3.jsonl
      - train_manifests/manifest_cleaned_YouTubeFr_casepunc_max30_split4.jsonl
      - train_manifests/manifest_cleaned_YouTubeFr_casepunc_max30_split5.jsonl
      - train_manifests/manifest_cleaned_YouTubeFr_casepunc_max30_split6_train.jsonl
      - train_manifests/manifest_cleaned_YODAS_casepunc_max30_fr000.jsonl
    tarred_audio_filepaths: null
    use_lhotse: false
    is_tarred: false
    sample_rate: ${model.sample_rate}
    batch_size: 50
    shuffle: true
    num_workers: 4
    pin_memory: true
    max_duration: 30.1
    min_duration: 0.1
    shuffle_n: 4096

  validation_ds:
    manifest_filepath: 
      - manifest_YouTubeFr_casepunc_max30_split6_dev.jsonl
      - manifest_VoxPopuli_casepunc_max30_dev.jsonl
      - manifest_Multilingual_TEDx_casepunc_max30_dev.jsonl
      - manifest_CommonVoice_casepunc_max30_dev.jsonl
    sample_rate: ${model.sample_rate}
    batch_size: 32
    shuffle: false
    use_start_end_token: false
    num_workers: 4
    pin_memory: true

  test_ds:
    manifest_filepath: null
    sample_rate: ${model.sample_rate}
    batch_size: 16
    shuffle: false
    use_start_end_token: false
    num_workers: 4
    pin_memory: true

  tokenizer:    # use for spe/bpe based tokenizer models
    update_tokenizer: false
    dir: stt_fr_fastconformer_hybrid_large_pc  # path to directory which contains either tokenizer.model (bpe) or vocab.txt (for wpe)
    type: bpe   # Can be either bpe (SentencePiece tokenizer) or wpe (WordPiece tokenizer)

  spec_augment:
    _target_: nemo.collections.asr.modules.SpectrogramAugmentation
    freq_masks: 2   # set to zero to disable it
    time_masks: 10  # set to zero to disable it
    freq_width: 27
    time_width: 0.05

  optim:
    name: adamw
    lr: 1e-5
    # optimizer arguments
    betas: [0.9, 0.98]
    weight_decay: 1e-3

    # scheduler setup
    sched:
      name: CosineAnnealing
      # scheduler config override
      warmup_steps: 1000
      warmup_ratio: null
      min_lr: 1e-6

trainer:
  devices: -1 # number of GPUs, -1 would use all available GPUs
  num_nodes: 1
  max_steps: 100_000 # computed at runtime if not set
  val_check_interval: 5000  # Set to 0.25 to check 4 times per epoch, or an int for number of iterations
  accelerator: auto
  strategy: ddp
  accumulate_grad_batches: 4
  gradient_clip_val: 1.0
  precision: bf16-mixed   # 16-mixed, 32, or bf16
  log_every_n_steps: 10   # Interval of logging.
  # use_distributed_sampler: False
  enable_progress_bar: True
  num_sanity_val_steps: 5     # number of steps to perform validation steps for sanity check the validation process before starting the training, setting to 0 disables it
  check_val_every_n_epoch: 1  # number of evaluations on validation every n epochs
  sync_batchnorm: true
  enable_checkpointing: False  # Provided by exp_manager
  logger: false     # Provided by exp_manager
  benchmark: false  # needs to be false for models with variable-length speech input as it slows down training
  fast_dev_run: false


exp_manager:
  exp_dir: nemo_experiments
  name: ${name}
  create_tensorboard_logger: true
  create_checkpoint_callback: true
  create_early_stopping_callback: false
  checkpoint_callback_params:
    monitor: "step"     # "val_wer" "train_loss"
    mode: "max"
    save_top_k: -1
    always_save_nemo: false
    save_last: true
    every_n_epochs: null
    every_n_train_steps: 5_000
    filename: training-{epoch:02d}-{step:06d}
  resume_if_exists: true
  resume_ignore_no_checkpoint: true
  max_time_per_run: 00:19:45:00

  create_wandb_logger: false
  wandb_logger_kwargs:
    name: null
    project: null